Add menu item for loading GLTF files
bevyengine/bevy_editor_prototypes pull request #124
Opened 2024-10-24 17:32 UTC by tim-blackbird

I originally wanted to integrate this into the asset browser, but that is tricky and needs more design work.
So, here is a temporary kludge to add a button at the end of the menu bar.

This button opens the native file-picker and allows you to select a 'gltf' or 'glb' file, if a file is selected then the first scene in that file will be loaded and spawned.

I've replaced the default cube with a plane to it doesn't overlap with the loaded scene.

> [!NOTE]  
> While this would be nice to have now, it's not strictly necessary and we could instead wait to add this functionality when we have fleshed out the assets browser.

### Showcase
![image](https://github.com/user-attachments/assets/32518fae-46cf-4552-9e91-7b7d938be31c)

### Future Work
- This code is in the wrong crate entirely
- We need a way to add 'actions' to asset types in the asset browser

2024-10-24 18:00 UTC, Atlas16A requested changes
I'd merge this after its moved to a more appropriate crate, perhaps the main bevy_editor crate? It could even live as an example under it. 

To avoid circular deps, put a marker component on it and import that component into main (at least for now)

2024-10-25 03:38 UTC, n1ght-hunter commented
i would recommend bevy_editor_utils. we are going to need more things like this anyways.

2024-10-25 11:30 UTC, hcabel commented
Yeah what's been holding my hand on the AssetBrowser is **where is the project related stuff is going to go?**
Then I'm more than happy to work something out to drag and drop asset in the viewport to spawn them

2024-10-25 11:33 UTC, Atlas16A commented
> Yeah what's been holding my hand on the AssetBrowser is **where is the project related stuff is going to go?**
> Then I'm more than happy to work something out to drag and drop asset in the viewport to spawn them
>  

Make an entirely separate bevy rust project directory outside the editor repo, that's your target for the asset browser, aka "target any arbitrary path and search for a assets folder"

2024-10-25 12:45 UTC, tim-blackbird commented
The code has been moved to `bevy_editor`. 
I've removed the `Load GLTF` button from the menu bar. Instead, you can now:
- Press `Ctrl + L` to `L`oad a file via the native file-picker, or
- Load a file by dropping it on the window
  Note: Not supported on wayland: https://github.com/rust-windowing/winit/issues/1881

> i would recommend bevy_editor_utils. we are going to need more things like this anyways.

I'd rather not add a `utils` crate if we can help it. The code in this PR is entirely temporary, it will be reworked soon enough, so lets not add a crate just for it.

2024-10-25 13:35 UTC, merged